### ISSUE TITLE
Error occurred at 1.0.6 when convert to SHIFT_JISX0213

### ISSUE THREAD

**Issue by krororo** [ruby/iconv#16]
reproduction code:
```ruby
require 'bundler/inline'

gemfile do
  gem 'iconv', '1.0.6'
end

i = Iconv.new('SHIFT_JISX0213', 'UTF-8')
ret = i.iconv('ほげ')
ret << i.iconv(nil)
p ret
i.close
```

ran:
```
Traceback (most recent call last):
	1: from /tmp/iconv.rb:8:in `<main>'
/tmp/iconv.rb:8:in `iconv': no implicit conversion of nil into String (TypeError)
```

but iconv 1.0.5 nothing was raised.

**Comment by nurse** [comment]
Fixed at v1.0.7. Thank you for reporting!
